# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Zip' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! # Add this if you are targeting iOS 8+ or using Swift

  # Pods for Remote

  # Fundamental
  pod 'RxSwift',    '~> 4.0'            		# RxSwift
  pod 'RxCocoa',    '~> 4.0'

end
