# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSimpleLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSimpleLogin
  # Fundamental
  pod 'RxSwift',    '~> 4.0'            # RxSwift
  pod 'RxCocoa',    '~> 4.0'

  target 'RxSimpleLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSimpleLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
